name: Create Javadoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '17'
       cache: 'gradle'
    - run: ./gradlew build --no-daemon
    - run: javadoc private -d ./internalConfigJavaDoc org.example
