name: Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '8'
       cache: 'gradle'
    - run: ./gradlew build --no-daemon
    - run: rmdir docs
    - run: mkdir docs
    - run: javadoc -private -d docs -subpackages ./src/main/java/org/example/models/*
    - run: git config --global user.email "omric@netapp.com"
    - run: git config --global user.name "omricospot"
    - run: git commit -a -m 'commit'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.OMRI_TOKEN }}
          force_with_lease: false
